# Generated by Django 4.2.14 on 2024-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('include_uppercase', models.BooleanField(default=True)),
                ('include_lowercase', models.BooleanField(default=True)),
                ('include_numbers', models.BooleanField(default=True)),
                ('include_special', models.BooleanField(default=True)),
                ('generated_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
